# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  branch-to-test:  # id of input
    description: 'which branch in the repo should be tested'
    required: true
    default: 'master'
#outputs:
#  time: # id of output
#    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.branch-to-test}}
