# action.yml
name: 'run tests in dockerfile'
description: 'install bindings and run tests on dockerfile'

inputs:
  dockerfile:
    description: 'which dockerfile to use'
    required: true
  branch-to-test:  # id of input
    description: 'which branch in the repo should be tested'
    required: true
    default: 'master'
  ao-token-prod:
    description: 'appoptics token valid in production environment'
    required: true

outputs:
  result:
    description: 'result from build-and-test-bindings.sh'

runs:
  using: 'docker'
  image: ${{dockerfile}}.Dockerfile
  args:
    - ${{inputs.branch-to-test}}
    - ${{inputs.ao-token-prod}}
